### ISSUE TITLE
Check performance from China and improve if it is slow

### ISSUE THREAD

**Issue by xicri** [xicri/genshin-dictionary#12]
I hear it is slow to access from China mainland to the foreign websites.

Genshin Dictionary is hosted by Cloudflare and it provides free global CDN, but the China data center is not available unless I bought the most expensive Enterprise plan.
Therefore, the Dictionary is probably served for users in China mainland from the foreign data centers. (Maybe Hong Kong or South Korea?)

# Prerequisite
#6

# Steps

- [ ] 1. Check performance (pagespeed) on access from China
  - Check Largest Contentful Paint using real-user monitoring (RUM).
- [ ] 2. Consider how can I resolve the performance problem.
  - Option 1. Serve from a server or CDN in China
    - ⚠ Is there any free or cheap static server or CDN?
    - ❌ Can I register ICP Beian?
  - Option 2. set up PWA to cache everything
    - It should be slow on first access, but faster from next access.

**Comment by Bill-Haku** [comment]
https://user-images.githubusercontent.com/48173350/182012360-bd088589-1db2-4564-b790-c49ece45888f.mp4

Maybe this screen record can be helpful.

I seldom access this site on my iPhone and it should not have loaded it from the cache. Of course, I didn't use VPN. My ISP is China Telecom.

> Therefore, the Dictionary is probably served for users in China mainland from the foreign data centers. (Maybe Hong Kong or South Korea?)

I tried a trace route tool and found that maybe it's provided by data centers at Los Angles😂
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/48173350/182013005-f9b916db-19e7-4607-861a-3e1234e0064e.png">

**Comment by xicri** [comment]
@Bill-Haku Thanks for your investigation!

Oh, the Dictionary is served from California? Maybe Cloudflare's routing does not work properly in China without purchasing the China Network option :sob:

According to your screen record, it seems to take about 4s for Visually Complete (The time when the browser completes rendering Above the Fold) and about 6s for Load.
Hmm, it's not terrible, but still slow.

Since it is probably not possible to serve from China, we can't provide the best performance for Chinese users, but hopefully, we need a bit faster performance.

**Comment by Bill-Haku** [comment]
I think the performance now is acceptable. You don't need to worry too much about it.

**Comment by xicri** [comment]
@Bill-Haku You are right, I will consider the performance when I have time.

**Comment by iamPorter** [comment]
There are some servers like Aliyun and Tencent Cloud. Chinese government has strict restrictions on Internet services. You can try, but I don't think it's a good choice.
You know there is something called "Beian"（[ICP备案](https://beian.miit.gov.cn/)）。It's not easy to get as you are an Japanese. Besides, it's a must for internal website but not a must for foreign ones. 
If you really want to apply for ICP Beian, [you can read this.](https://help.aliyun.com/document_detail/65265.html)（Chinese page）
And I'm sorry to tell you that owing ICP won't boost Internet connection.

**Comment by Bill-Haku** [comment]
In fact foreigners can also apply for an ICP beian, and then a CDN server can be deployed in China. But as it may take a lot time, it is really not something should be done with a high priority.

**Comment by xicri** [comment]
@iamPorter Thanks for the information!

I want to make the Dictionary as fast as the websites hosted in China mainland because [slow pagespeed causes higher bounce rates](https://www.section.io/blog/page-load-time-bounce-rate/), but as you pointed out, it is difficult because of the problem in my Chinese language skill.

As you mentioned, loading in 4 to 6 seconds are normal for people in China mainland, so maybe we can accept current pagespeed for now.

> And I'm sorry to tell you that owing ICP won't boost Internet connection.

Yes, you are right. I meant I wanted to sign up with ICP Baian to host Genshin Dictionary on the server in China mainland. Hosting on the China server should improve the pagespeed.
