### ISSUE TITLE
Translate /about & /opendata to Chinese

### ISSUE THREAD

**Issue by xicri** [xicri/genshin-dictionary#246]
Currently, the Simplified Chinese versions of the doc pages are mostly the same as the English versions. I will ask @Crepveant to translate these pages to Simplified Chinese.

- https://genshin-dictionary.com/zh-CN/about
- https://genshin-dictionary.com/zh-CN/opendata

The translation code is located at:
- https://github.com/xicri/genshin-dictionary/blob/main/pages/about.vue#L98-L116
- https://github.com/xicri/genshin-dictionary/blob/main/pages/opendata.vue#L200-L249

I recommend rebasing or resetting your branch. If you are not familiar with the rebase and reset of Git, I think it is the easiest to fork this repository again.

**Comment by xicri** [comment]
@Crepveant As always, it is not an urgent task.
Please work on this Issue when you are free.
I guess you are busy with your school... and maybe exploring the new area of Natlan :sunglasses:

**Comment by Crepveant** [comment]
> and exploring the new area of Natlan 😎

Not exactly…

I’ve been busy with 中考 (a bit like 高校受験) prep for 4 months and haven’t touched any games 🫠

This will probably last until June 2025 (maybe April if lucky), so I might light Natlan’s first Statue of the Seven while you’re already in Snezhnaya 🥴

**Comment by xicri** [comment]
@Crepveant Oh, then you are very busy until next June.
Hope you successfully pass the 中考 exam.
