### ISSUE TITLE
Chinese Pinyin only display the last one when there are multiple pinyin for a single word.

### ISSUE THREAD

**Issue by SleepyAsh0191** [xicri/genshin-dictionary#89]
![image](https://user-images.githubusercontent.com/64446140/233289377-a81c17b9-c2ba-4e3c-8ccc-e75173722ae2.png)
![image](https://user-images.githubusercontent.com/64446140/233289587-1413a2ed-8311-47a0-b845-edcc59b2a1a5.png)

**Comment by SleepyAsh0191** [comment]
And I found I made another mistake in my latest pr, will fix in next commit

**Comment by xicri** [comment]
Confirmed, I'll fixit. Thanks!

**Comment by xicri** [comment]
@SleepyAsh0191 I've fixed this. It should show all the pinyin now.

**Comment by xicri** [comment]
cc: @Bill-Haku

**Comment by Bill-Haku** [comment]
Thanks, it looks good now.
